version: '3.8'

services:
  backend:
    build:
      context: ./web/backend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./web/backend:/app
    environment:
      - RAILS_ENV=development
      - DATABASE_URL=mysql2://root:password@db:3306/my_library_system_development
      - REDIS_URL=redis://redis:6379/1
    depends_on:
      - db
      - redis

  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./web/frontend:/app
    environment:
      - VUE_APP_API_URL=http://localhost:3000/api

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=my_library_system_development
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: 