FROM ruby:3.2.2

# 必要なパッケージのインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs default-mysql-client \
    sqlite3 libsqlite3-dev

# 作業ディレクトリの設定
WORKDIR /app

# Gemfileのコピー
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

# Bundlerのインストールと実行
RUN gem install bundler:2.6.8
RUN bundle config set --local deployment 'false' && \
    bundle config set --local force_ruby_platform true && \
    bundle install

# アプリケーションのコピー
COPY . /app

# Railsサーバーの起動
CMD ["rails", "server", "-b", "0.0.0.0"] 