name: my_library_system_fsystem
description: Frontend system for My Library System
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0
  path_provider: ^2.1.0
  json_annotation: ^4.8.0
  barcode_scanner: ^0.0.1
  dio: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 