apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - mysql-deployment.yaml
  - redis-deployment.yaml
  - ingress.yaml

commonLabels:
  app: my-library-system 